version: '2'
services:
   kibana:
      image: kibana:latest
      ports:
         - "5601"
      depends_on:
         - elasticsearch
      networks:
         - docker_elk
   elasticsearch:
      image: elasticsearch:latest
      ports:
         - "9200"
         - "9300"
      networks:
         - docker_elk
   prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        networks:
           - docker_elk
   influxdb:
     image: library/influxdb
     ports:
       - "8083:8083"
       - "8086:8086"
     networks:
        - docker_elk
   grafana:
        image: grafana/grafana
        ports:
           - "3000"
        networks:
           - docker_elk

networks:
  docker_elk:
    driver: bridge
